<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvvevrc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvvevrc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBvvevrc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBvvevrc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBvvevrc\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bvvevrc',
    'container.build_id' => '7e00e2b5',
    'container.build_time' => 1532272510,
));
